name: Java CI for Robotix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: 
          ${{ runner.os }}-maven-

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99

    - name: List directory contents
      run: ls -R Application/Robotix
      
    - name: Build and test with Maven
      run: mvn clean test -DargLine="--add-opens java.base/java.time=com.google.gson"

    - name: Build and test with Maven
      run: mvn -B test -DargLine="--add-opens java.base/java.time=com.google.gson"
      working-directory: Application/Robotix

    # Optional: Increase Maven's logging verbosity to debug issues
    - name: Run Maven with Debug Logging
      run: mvn -X test
      working-directory: Application/Robotix