name: Java CI for Robotix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: 
          ${{ runner.os }}-maven-

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &
        sleep 5

    - name: Build and test with Maven
      working-directory: Application/Robotix
      run: |
        mvn -B test -Dtest=SimpleTest -DargLine="--add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens java.base/java.util.function=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED"

    - name: Run Maven with Debug Logging
      working-directory: Application/Robotix
      run: |
        mvn -X verify